package com.seopulse.report;

import com.seopulse.report.render.PdfRenderer;
import com.seopulse.report.render.ReportHtmlRenderer;
import com.seopulse.report.render.ReportModel;
import com.seopulse.report.storage.FilesystemReportStorage;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.nio.charset.StandardCharsets;
import java.nio.file.Path;
import java.time.Instant;
import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

class ReportRenderingTest {

    private final ReportHtmlRenderer htmlRenderer = new ReportHtmlRenderer();

    @Test
    void htmlEscapesSiteContent() {
        String html = htmlRenderer.render(model(null, false, "<script>alert(1)</script>"));

        assertThat(html).doesNotContain("<script>alert(1)</script>").contains("&lt;script&gt;");
    }

    @Test
    void watermarkAndWhiteLabelChangeTheOutput() {
        String free = htmlRenderer.render(model(null, true, "Example"));
        assertThat(free).contains("SEOPulse Free").contains("Generated by SEOPulse");

        var branding = new ReportModel.Branding("Acme Agency", "#112233", "Prepared for Example Ltd", null);
        String branded = htmlRenderer.render(model(branding, false, "Example"));
        assertThat(branded).contains("Prepared by Acme Agency").contains("#112233").doesNotContain("SEOPulse");
    }

    @Test
    void invalidBrandColorsAndRemoteLogosAreIgnored() {
        var branding = new ReportModel.Branding("Acme", "red;}body{display:none", null, "https://evil.example/logo.png");
        String html = htmlRenderer.render(model(branding, false, "Example"));

        assertThat(html).doesNotContain("display:none").doesNotContain("evil.example");
    }

    @Test
    void rendersAPdfWithoutFetchingRemoteResources() throws Exception {
        String html = htmlRenderer.render(model(null, true, "Example"))
                .replace("</body>", "<img src=\"http://127.0.0.1:1/x.png\"/><link rel=\"stylesheet\" href=\"file:///etc/passwd\"/></body>");

        byte[] pdf = new PdfRenderer().render(html);

        assertThat(new String(pdf, 0, 5, StandardCharsets.US_ASCII)).isEqualTo("%PDF-");
    }

    @Test
    void filesystemStorageRejectsPathTraversal(@TempDir Path dir) throws Exception {
        FilesystemReportStorage storage = new FilesystemReportStorage(dir);
        storage.put("reports/1/2/3.pdf", new byte[]{1, 2, 3});

        assertThat(storage.get("reports/1/2/3.pdf")).containsExactly(1, 2, 3);
        assertThatThrownBy(() -> storage.get("../outside.pdf")).isInstanceOf(IllegalArgumentException.class);
        assertThatThrownBy(() -> storage.put("reports/../../x.pdf", new byte[0])).isInstanceOf(IllegalArgumentException.class);
    }

    private static ReportModel model(ReportModel.Branding branding, boolean watermark, String name) {
        return new ReportModel(
                7L, name, "https://example.com", Instant.parse("2026-10-01T10:00:00Z"),
                82, 2, Map.of("CONTENT", 90, "TECHNICAL", 75), 12, 5, 1, 3, 1, 78, 2, 1, true,
                List.of(new ReportModel.RuleGroup("TITLE_MISSING", "Missing title", "ERROR", "CONTENT", 1,
                        "Add a title", null, List.of("https://example.com/a"))),
                branding, watermark);
    }
}
