import { http, HttpResponse } from 'msw'
import { screen } from '@testing-library/react'
import { Route, Routes } from 'react-router-dom'
import { describe, expect, it } from 'vitest'

import type { SharedReport } from '@/api/publicReports'
import { SharedReportPage } from '@/pages/SharedReportPage'
import { renderWithProviders } from '@/test/render'
import { api, server } from '@/test/server'

function report(overrides: Partial<SharedReport> = {}): SharedReport {
  return {
    auditId: 9,
    websiteName: 'Example',
    websiteUrl: 'https://example.com',
    completedAt: '2026-09-02T10:00:00Z',
    score: 82,
    scoreVersion: 2,
    categoryScores: { CONTENT: 90, TECHNICAL: 70 },
    pagesCrawled: 12,
    issueCount: 3,
    errorCount: 1,
    warningCount: 1,
    infoCount: 1,
    previousScore: 78,
    newIssues: 1,
    fixedIssues: 2,
    detailsAvailable: true,
    topIssues: [
      {
        ruleCode: 'MISSING_TITLE',
        title: 'Missing title',
        severity: 'ERROR',
        category: 'CONTENT',
        count: 1,
        recommendation: 'Add a title',
        helpUrl: null,
        sampleUrls: ['https://example.com/about'],
      },
    ],
    branding: { companyName: 'Acme Agency', brandColor: '#112233', coverText: 'Prepared for Example', logoDataUrl: null },
    watermark: false,
    ...overrides,
  }
}

function renderAt(token: string) {
  return renderWithProviders(
    <Routes>
      <Route path="/r/:token" element={<SharedReportPage />} />
    </Routes>,
    { route: `/r/${token}`, withAuth: false },
  )
}

describe('SharedReportPage', () => {
  it('renders a white-labelled report without signing in', async () => {
    server.use(http.get(api('/public/reports/tok123'), () => HttpResponse.json(report())))
    renderAt('tok123')

    expect(await screen.findByRole('heading', { name: 'Example' })).toBeInTheDocument()
    expect(screen.getByText('Acme Agency')).toBeInTheDocument()
    expect(screen.getByText('Prepared by Acme Agency')).toBeInTheDocument()
    expect(screen.getByText('Missing title')).toBeInTheDocument()
    expect(screen.getByText('+4 since previous audit')).toBeInTheDocument()
    expect(screen.getByRole('link', { name: /Download PDF/ })).toHaveAttribute(
      'href',
      api('/public/reports/tok123/pdf'),
    )
  })

  it('shows the Free watermark', async () => {
    server.use(
      http.get(api('/public/reports/free'), () => HttpResponse.json(report({ branding: null, watermark: true }))),
    )
    renderAt('free')
    expect(await screen.findByText('Generated with SEOPulse Free')).toBeInTheDocument()
    expect(screen.getByText('Generated by SEOPulse')).toBeInTheDocument()
  })

  it('explains revoked or expired links', async () => {
    server.use(http.get(api('/public/reports/gone'), () => HttpResponse.json({ status: 404 }, { status: 404 })))
    renderAt('gone')
    expect(await screen.findByText('Report not available')).toBeInTheDocument()
  })
})
